#---------------------------------------------------------------------------------
.SUFFIXES:
#---------------------------------------------------------------------------------
ifeq ($(strip $(DEVKITARM)),)
$(error "Please set DEVKITARM in your environment. export DEVKITARM=<path to>devkitARM)
endif

include $(DEVKITARM)/ds_rules
all:
	@$(MAKE) -f Makefile
install:
	@$(MAKE) -f Makefile install-ds
clean:
	@$(MAKE) -f Makefile clean
