#---------------------------------------------------------------------------------
.SUFFIXES:
#---------------------------------------------------------------------------------
ifeq ($(strip $(DEVKITPPC)),)
$(error "Please set DEVKITPPC in your environment. export DEVKITPPC=<path to>devkitPPC)
endif

include $(DEVKITPPC)/wii_rules
all:
	@$(MAKE) -f Makefile
install:
	@$(MAKE) -f Makefile install-ppc
clean:
	@$(MAKE) -f Makefile clean
