#---------------------------------------------------------------------------------
.SUFFIXES:
#---------------------------------------------------------------------------------
ifeq ($(strip $(DEVKITARM)),)
$(error "Please set DEVKITARM in your environment. export DEVKITARM=<path to>devkitARM)
endif

include $(DEVKITARM)/gp32_rules
all:
	@$(MAKE) -f Makefile
install:
	@echo "Cannot install with gp32 target."
clean:
	@$(MAKE) -f Makefile clean
